Add (de)serialization for Property/Records
SamboyCoding/Tomlet pull request #8
Opened 2021-08-04 19:50 UTC by M3rs

Properties have a backing field named like '<MyField>k__BackingField'
which can get used for properties and record types.

i.e.

```
public class MyClass
{
	public string MyString { get; set; }
}
```

When looking at `typeof(MyClass)`, there will be a private field
`private string <MyString>k__BackingField`.

- Add to `GetCompositeDeserializer` and `GetCompositeSerializer` the
  ability to read properties.
- Add to tests examples of class with Properties and record type

2021-08-04 19:56 UTC, SamboyCoding requested changes
Please gitignore your .vs folder - test logs and user-specific configuration should not be pushed.

2021-08-04 19:58 UTC, SamboyCoding requested changes

2021-08-04 19:58 UTC, SamboyCoding commented on Tomlet/TomlSerializationMethods.cs
> +                var fields = type.GetFields(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.SetProperty);
I don't think this change is required, `SetProperty` only applies when calling methods, from what I can see on the docs, and regardless your change isn't required by the code you wrote below.

2021-08-04 19:58 UTC, SamboyCoding commented on Tomlet/TomlSerializationMethods.cs
> +                var fields = type.GetFields(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.GetProperty);
Same as above, I don't think `GetProperty` needs to be specified here.

2021-08-04 19:59 UTC, SamboyCoding commented
Other than those minor details, nice PR! Very appreciated, and thanks for writing additional tests too.

2021-08-04 20:21 UTC, M3rs commented
Ah, good call out on the BindingFlags. Cleaned up that and the gitignore.

2021-08-04 20:23 UTC, SamboyCoding approved these changes

2021-08-04 20:23 UTC, SamboyCoding commented
Alright, merging this now, will try and get a release out tonight.

2021-08-04 20:23 UTC, merged

2021-08-04 20:25 UTC, SamboyCoding commented
As a slight aside, your local git email doesn't match your github one, so these commits aren't attributed to you.

2021-08-04 20:36 UTC, M3rs commented
Ah, I'll get that sorted, thanks

2021-08-16 13:59 UTC, SamboyCoding commented
This is now live in 2.0.0. Sorry for the delay in getting this out in a release!